spring:
  datasource:
    url: jdbc:mysql://192.168.1.181:3306/saas-user-center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: Db_Zz_123_Db_Zz_123_Db_Zz_123_
#    driver-class-name: com.mysql.cj.jdbc.Driver